### ISSUE TITLE
Aim Correction doesnt work after hotfix

### ISSUE THREAD

**Issue by Desik000** [Airi85/OsuMultiTool#10]
Just tested 4 maps and seems like aimcorrection just teleports the mouse randomly to places where the notes are not, im going to try more maps

**Comment by Airi85** [comment]
osu! sensibility is 1?

**Comment by Desik000** [comment]
It is not however it worked before, but well i will set it to 1 i dont have any problems with that.. going to test it now, will let you know if it works

**Comment by ninja1234567** [comment]
where is the hotfix?

**Comment by Desik000** [comment]
-Fixed, thanks alot

**Comment by Desik000** [comment]
ninja, version 0.3d

**Comment by Airi85** [comment]
its working with you defaulty sensibility now?, sensibility change screen coords but having a sensibility close to 1 like 1.19 should still work

**Comment by Desik000** [comment]
Airi85  The problem was that i was using RAW Input on, sorry for this..

**Comment by Desik000** [comment]
Basically anyone who upgraded to windows 10 cant use any other sens than 1.0 without having Raw input on, so if anyone else is having this problem you gotta set it to 1 and raw input off

**Comment by Airi85** [comment]
i need to install win 10 later for testing..

**Comment by Desik000** [comment]
If you want me to try to do some stuff or something just tell me

**Comment by ninja1234567** [comment]
Line 4317
Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded.

**Comment by Airi85** [comment]
ok ^^
