### ISSUE TITLE
Can't view full difficulty names when its needed

### ISSUE THREAD

**Issue by Desik000** [Airi85/OsuMultiTool#15]
Hey, i just noticed that some maps have difficulties starting with a long name, and you cant tell which is the difficulty which you are looking for (which can be really important in multiplayer)  . Maybe the full name could show when we hover on it?

This is what i mean:
https://ctrlv.cz/shots/2015/08/03/UNYL.png

**Comment by Airi85** [comment]
i'll redo the GUI, need to add some things also
