### ISSUE TITLE
Airman ga Taosenai bad aim on stream

### ISSUE THREAD

**Issue by throwaway1233** [Airi85/OsuMultiTool#5]
Hey, it's me again.
I noticed that the bot has wrong aim on the stream after the 1st break on CRN's Extra diff on Airman ga Taosenai soundholic version. It is just off so it doesn't hit the notes. Also happened in EWF TIme Freeze but managed to pass that though. Looks like this.
![screenshot081](https://cloud.githubusercontent.com/assets/13337899/8827781/e85b9e7c-308e-11e5-92ee-0382763b7563.jpg)

**Comment by Airi85** [comment]
stack calculation is a bit wrong, will be fixed
