### ISSUE TITLE
relax Settings?

### ISSUE THREAD

**Issue by Desik000** [Airi85/OsuMultiTool#6]
Hey, what settings are the best to use for relax? im talking about the min and max ms delay or w/e it is, when its on 0-50 its easy to hit notes but alot of them are 100, with 0-5 its hard to hit notes but everything is 300.. what settings do you recommend please? Thanks and this tool is the best :+1:

**Comment by throwaway1233** [comment]
i use 0-12 with aimbot, but I'd recommend something about 18 or 20 for just relax

**Comment by Airi85** [comment]
you can use negative numbers too, -10 to 20 should give only 300 and easier to hit

**Comment by Airi85** [comment]
OD10 songs anything higher then 17 will give 100 or 50 tho

**Comment by Desik000** [comment]
Thank you! You are really amazing
