### ISSUE TITLE
Keyboard buttons

### ISSUE THREAD

**Issue by asdaskadg** [Airi85/OsuMultiTool#8]
Error code 5454 when changing keyboard button.

Error: Array variable has incorrect number of subscripts or subscript dimension range exceeded.

Help please

**Comment by Airi85** [comment]
use 0.3b for keyboard buttons

**Comment by asdaskadg** [comment]
What? I don't understand.

**Comment by Airi85** [comment]
version 0.3b, keyboard buttons is bugged on 0.3c

**Comment by asdaskadg** [comment]
Oh okay, gotcha.
